In [6]:
import pandas
import os
os.listdir()

['.idea',
 '.ipynb_checkpoints',
 'intro.py',
 'pandas.iml',
 'supermarkets-commas.txt',
 'supermarkets-semi-colons.txt',
 'supermarkets.csv',
 'supermarkets.json',
 'supermarkets.xlsx',
 'Untitled.ipynb']

In [10]:
df1 = pandas.read_csv('supermarkets.csv')
df1

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [12]:
df2 = pandas.read_json('supermarkets.json')
df2

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [17]:
df3 = pandas.read_excel('supermarkets.xlsx')
df3

ID          Address           City             State Country  \
0   1     3666 21st St  San Francisco          CA 94114     USA   
1   2   735 Dolores St  San Francisco          CA 94119     USA   
2   3      332 Hill St  San Francisco  California 94114     USA   
3   4     3995 23rd St  San Francisco          CA 94114     USA   
4   5  1056 Sanchez St  San Francisco        California     USA   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   

  Supermarket Name  Number of Employees  
0          Madeira                    8  
1      Bready Shop                   15  
2      Super River                   25  
3       Ben's Shop                   10  
4          Sanchez                   12  
5       Richvalley                   20

In [19]:
df4 = pandas.read_csv('supermarkets-commas.txt')
df4

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [21]:
df5 = pandas.read_csv('supermarkets-semi-colons.txt', sep=';')
df5

ID          Address           City             State Country          Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA       Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA   Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA   Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA    Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA       Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA    Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [23]:
df6 = pandas.read_csv('data.txt', sep=';', header=None)
df6

0                1              2                 3    4             5   6
0  1     3666 21st St  San Francisco          CA 94114  USA       Madeira   8
1  2   735 Dolores St  San Francisco          CA 94119  USA   Bready Shop  15
2  3      332 Hill St  San Francisco  California 94114  USA   Super River  25
3  4     3995 23rd St  San Francisco          CA 94114  USA    Ben's Shop  10
4  5  1056 Sanchez St  San Francisco        California  USA       Sanchez  12
5  6  551 Alvarado St  San Francisco          CA 94114  USA    Richvalley  20

In [26]:
df6.columns = ['ID', 'Adress', 'City', 'State', 'Country', 'Name', 'Employees']
df6

ID           Adress           City             State Country          Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA       Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA   Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA   Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA    Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA       Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA    Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [31]:
df7 = df6.set_index('ID')  #not in place you can use inplace=True to do it in place,
# also use drop=False to not drop columns that are old indexes
df7

Adress           City             State Country          Name  \
ID                                                                           
1      3666 21st St  San Francisco          CA 94114     USA       Madeira   
2    735 Dolores St  San Francisco          CA 94119     USA   Bready Shop   
3       332 Hill St  San Francisco  California 94114     USA   Super River   
4      3995 23rd St  San Francisco          CA 94114     USA    Ben's Shop   
5   1056 Sanchez St  San Francisco        California     USA       Sanchez   
6   551 Alvarado St  San Francisco          CA 94114     USA    Richvalley   

    Employees  
ID             
1           8  
2          15  
3          25  
4          10  
5          12  
6          20

In [35]:
df7.loc['2': '5', 'State':'Country']

State Country
ID                          
2           CA 94119     USA
3   California 94114     USA
4           CA 94114     USA
5         California     USA

In [41]:
df7.iloc[2:4, 0:4]  # pandas unlike std python slice inlude last value in output of slice

Adress           City             State Country
ID                                                       
3    332 Hill St  San Francisco  California 94114     USA
4   3995 23rd St  San Francisco          CA 94114     USA

In [42]:
 df8 = df7.drop('City', 1) # not in place 1 to delete cols, 0 rows

In [43]:
df8

Adress             State Country          Name  Employees
ID                                                                    
1      3666 21st St          CA 94114     USA       Madeira          8
2    735 Dolores St          CA 94119     USA   Bready Shop         15
3       332 Hill St  California 94114     USA   Super River         25
4      3995 23rd St          CA 94114     USA    Ben's Shop         10
5   1056 Sanchez St        California     USA       Sanchez         12
6   551 Alvarado St          CA 94114     USA    Richvalley         20

In [45]:
df8['Continent'] = ['North America', 'North America', 'North America', 'North America', 'North America', 'North America']
df8 # whoa

Adress             State Country          Name  Employees  \
ID                                                                       
1      3666 21st St          CA 94114     USA       Madeira          8   
2    735 Dolores St          CA 94119     USA   Bready Shop         15   
3       332 Hill St  California 94114     USA   Super River         25   
4      3995 23rd St          CA 94114     USA    Ben's Shop         10   
5   1056 Sanchez St        California     USA       Sanchez         12   
6   551 Alvarado St          CA 94114     USA    Richvalley         20   

        Continent  
ID                 
1   North America  
2   North America  
3   North America  
4   North America  
5   North America  
6   North America

In [47]:
# or else
df8['Random stuff'] = df8.shape[0] *['dcsa']
df8

Adress             State Country          Name  Employees  \
ID                                                                       
1      3666 21st St          CA 94114     USA       Madeira          8   
2    735 Dolores St          CA 94119     USA   Bready Shop         15   
3       332 Hill St  California 94114     USA   Super River         25   
4      3995 23rd St          CA 94114     USA    Ben's Shop         10   
5   1056 Sanchez St        California     USA       Sanchez         12   
6   551 Alvarado St          CA 94114     USA    Richvalley         20   

        Continent Random stuff  
ID                              
1   North America         dcsa  
2   North America         dcsa  
3   North America         dcsa  
4   North America         dcsa  
5   North America         dcsa  
6   North America         dcsa

In [51]:
import numpy

n = numpy.arange(27)

n.reshape(3,3,3)



array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [53]:
import cv2
im_grey = cv2.imread('smallgray.png', 0)
im_grey



array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [54]:
im_grey = cv2.imread('smallgray.png', 1)
print(im_grey)

[[[187 187 187]
  [158 158 158]
  [104 104 104]
  [121 121 121]
  [143 143 143]]

 [[198 198 198]
  [125 125 125]
  [255 255 255]
  [255 255 255]
  [147 147 147]]

 [[209 209 209]
  [134 134 134]
  [255 255 255]
  [ 97  97  97]
  [182 182 182]]]
